/* Regenerated from original/ZombieSlaughter/data.dat by dat_extract. Do not hand edit. */

#define AAAPAL                       0    /* PAL  */
#define BMP_BONE1                    1    /* BMP  */
#define BMP_BONE2                    2    /* BMP  */
#define BMP_BONE3                    3    /* BMP  */
#define BMP_BULLET                   4    /* BMP  */
#define BMP_CROSSHAIR                5    /* BMP  */
#define BMP_DYNAMITE                 6    /* BMP  */
#define BMP_FLAME                    7    /* BMP  */
#define BMP_FLAME_MASK               8    /* BMP  */
#define BMP_GUN                      9    /* BMP  */
#define BMP_GUNL                     10   /* BMP  */
#define BMP_HELP                     11   /* BMP  */
#define BMP_HERO_GUN                 12   /* BMP  */
#define BMP_HUD                      13   /* BMP  */
#define BMP_HUD_CUR                  14   /* BMP  */
#define BMP_ITEM                     15   /* BMP  */
#define BMP_ITEM_D                   16   /* BMP  */
#define BMP_ITEM_F                   17   /* BMP  */
#define BMP_ITEM_H                   18   /* BMP  */
#define BMP_LND_TOP                  19   /* BMP  */
#define BMP_TILE1                    20   /* BMP  */
#define BMP_TITLE                    21   /* BMP  */
#define BMP_ZOMBIE                   22   /* BMP  */
#define BMP_ZOMBIE_MASK              23   /* BMP  */
#define FNT_BIG                      24   /* FONT */
#define FNT_SMALL                    25   /* FONT */
#define SMP_AH                       26   /* SAMP */
#define SMP_AUO                      27   /* SAMP */
#define SMP_CLICK                    28   /* SAMP */
#define SMP_EXPL                     29   /* SAMP */
#define SMP_FLAME1                   30   /* SAMP */
#define SMP_GRAVES                   31   /* SAMP */
#define SMP_JOIN                     32   /* SAMP */
#define SMP_JUMP                     33   /* SAMP */
#define SMP_SHOOT                    34   /* SAMP */
#define GrabberInfo                  35   /* info */
