char b[95][255]=
{"19 Random - eg. random levels and items; see how far you can take it ",
"16 Light & darkness ",
"13 genre mix - eg puzzle meets shootemup ",
"13 light - lasers & mirrors, reflection and refraction", 
"13 1 button ",
"12 at least 50 independent semi-intelligent moving objects ",
"11 gore, gib and blood ",
"11 evolution ",
"10 Flow - Fluids, electricity, etc. ",
"10 rescue ",
"10 black and white - use only two colors. ",
"10 escape ",
"10 four elements - earth, air, fire & water ",
"10 Mini games mania - a game composed out of an unholy amount of mini games that are connected ",
"10 32x32 Pixel Screen - From last compo. ",
"9 growth - Things That Grow ",
"9 martian invasion ",
"9 balance - physic or metaphysic ",
"8 procedural environment ",
"8 non-action - for instance, let the decisive interaction be made by remaining passive at the right moment/s ",
"8 wind - the concept of a fluctuating, unpredictable, invisible force is key. ",
"7 death ",
"7 gravity well ",
"7 ice as the playing surface ",
"6 slow motion - take anything that happens quickly, slow it down, and make a game out of it. ",
"6 Day & night ",
"6 square, circle, triangle - the basic shapes ",
"6 coercion - make forcing something/someone a key gameplay element", 
"6 underwater city ",
"6 hide - Don't let anybody notice you.", 
"6 Retro 3D - attempt to create a 3D game without only 2D graphics libraries (IE SDL/2D allegro but no GL/D3D)", 
"6 remote control - user input doesn't control the game's main character(s) directly but rather through some other means ",
"6 programming game - writing little programs ",
"5 Flight ",
"5 influence ",
"5 fire ",
"5 mechanics - cogs, springs, steampower, airpressure, etc; more limited than physical interaction ",
"5 water ",
"5 corruption ",
"5 mining for minerals ",
"5 social interaction ",
"5 substitution - replacing something with some other thing ",
"5 goop ",
"4 procedural story ",
"4 In a Tuxedo: Adventures of a penguin ",
"4 illusion ",
"4 love ",
"4 Floating ",
"4 delayed action ",
"4 collecting coins ",
"4 Wanton disregard for all law ",
"4 a bug's life ",
"4 Terraforming - turn a planet into a pizza ",
"4 card combat ",
"3 time", 
"3 orbits", 
"3 capture ",
"3 security guards ",
"3 autumn ",
"3 math & logic ",
"3 virtual pet ",
"3 stacking or connecting things ",
"3 sound - make sound a key gameplay element ",
"3 Audio Interface ",
"3 alchemy ",
"3 fear ",
"2 kitchen combat ",
"2 aging ",
"2 physical interaction ",
"2 chernobyl ",
"2 air ",
"2 repetition ",
"2 Edutainment ",
"2 airport ",
"2 honey i shrunk myself! ",
"2 matching colors ",
"2 land acquisition ",
"2 The anti-death ",
"2 Consumption ",
"1 hurricane season ",
"1 That tickly feeling in your stomach (not quite love) ",
"1 jewelry ",
"1 alphabet ",
"1 clothing ",
"1 joints ",
"1 life ",
"1 road trip ",
"1 reversals ",
"1 lunch hour ",
"1 Consumerism ",
"1 loch ness monster ",
"1 saturn's rings ",
"1 lemonade (NOT the original lemonade stand game!) ",
"1 Fun with agricultural appliances ",
"1 A foreign language - Linguistic puzzles"} ;